enum ModuleList
{
	MODULE_NONE = -1,
	MODULE_CAMERA_MANAGER = 0,
	MODULE_NOTIFICATION_MANAGER = 1,
	MODULE_SYSTEM_IO = 2,
	MODULE_NETWORK_MANAGER = 4,
	MODULE_QR_CODE_GENERATOR = 8,
	MODULE_OBJ_DETECTION_MANAGER = 16,
	MODULE_MAX = MODULE_OBJ_DETECTION_MANAGER
};
